---
- name: create ldap domain
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_DOMAIN_ID: default
  os_keystone_domain:
    name: "{{ keystone.ldap_domain.domain }}"
    auth:
      auth_url: "{{ endpoints.keystone.url.internal }}/v3"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password }}"
  run_once: true
  register: ldap_domain

- name: restart keystone to pick up ldap domain users
  service: name=keystone state=restarted

- name: create ldap project
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_DOMAIN_ID: default
  os_project:
    name: "{{ keystone.ldap_domain.project }}"
    domain_id: "{{ ldap_domain.domain.id }}"
    auth:
      auth_url: "{{ endpoints.keystone.url.internal }}/v3"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password }}"
  register: ldap_project
  run_once: true

- name: determine id of the ldap domain deploy user
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_DOMAIN_ID: default
  shell: . /root/stackrc; openstack --os-auth-url "{{ endpoints.keystone.url.internal }}/v3" user show --domain "{{ ldap_domain.id }}" "{{ keystone.ldap_domain.deploy_user }}"
  when: keystone.ldap_domain.enabled|default('False')|bool and keystone.ldap_domain.deploy_user != ""
  register: ldap_deploy_user
  run_once: true

- name: add domain admin role to the ldap domain deploy user
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_DOMAIN_ID: default
  shell: . /root/stackrc; openstack --os-auth-url "{{ endpoints.keystone.url.internal }}/v3" role add --domain "{{ ldap_domain.id }}" --user "{{ ldap_deploy_user.stdout.split('| id        | ')[1].split(' |')[0] }}" admin
  when: keystone.ldap_domain.enabled|default('False')|bool and keystone.ldap_domain.deploy_user != ""
  run_once: true

- name: add project admin role to the ldap domain deploy user
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_DOMAIN_ID: default
  shell: . /root/stackrc; openstack --os-auth-url "{{ endpoints.keystone.url.internal }}/v3" role add --project "{{ ldap_project.project.id }}" --user "{{ ldap_deploy_user.stdout.split('| id        | ')[1].split(' |')[0] }}" admin
  when: keystone.ldap_domain.enabled|default('False')|bool and keystone.ldap_domain.deploy_user != ""
  run_once: true
